# Generated by Django 2.1 on 2018-09-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='部门名称')),
                ('parent', models.CharField(max_length=32, verbose_name='父项ID')),
                ('orderid', models.IntegerField(default=0, verbose_name='顺序')),
                ('note', models.CharField(default='', max_length=64, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=32, null=True, verbose_name='姓名')),
                ('psex', models.IntegerField(default=0, null=True)),
                ('pbirthdays', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('ptel', models.CharField(default='', max_length=32, null=True, verbose_name='电话')),
                ('pemail', models.CharField(default='', max_length=32, null=True, verbose_name='邮箱地址')),
                ('paddress', models.CharField(default='', max_length=32, null=True, verbose_name='地址')),
                ('pstate', models.IntegerField(default=0, null=True, verbose_name='状态')),
                ('pdate', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('note', models.CharField(default='', max_length=64, null=True, verbose_name='备注')),
                ('org', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SysMGR.OrgInfo', verbose_name='所属部门')),
            ],
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=32)),
                ('note', models.CharField(default='', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('person', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SysMGR.PersonInfo')),
                ('role', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SysMGR.RoleInfo')),
            ],
        ),
    ]
