# Generated by Django 2.1 on 2018-09-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SysMGR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, null=True)),
                ('url', models.CharField(max_length=64, null=True)),
                ('level', models.IntegerField(default=0, null=True)),
                ('parent', models.CharField(max_length=32, null=True)),
                ('orderid', models.IntegerField(default=100, null=True)),
                ('note', models.CharField(default='', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolemenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=64, null=True)),
                ('menu', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SysMGR.MenuInfo')),
                ('role', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SysMGR.RoleInfo')),
            ],
        ),
    ]
