# Generated by Django 2.1 on 2018-09-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SysMGR', '0002_menuinfo_rolemenuinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(default='', max_length=64, null=True)),
                ('note', models.CharField(default='', max_length=64, null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SysMGR.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MessgeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messge', models.CharField(default='', max_length=64, null=True)),
                ('url', models.CharField(default='', max_length=64, null=True)),
                ('state', models.CharField(default='', max_length=32, null=True)),
                ('note', models.CharField(default='', max_length=64, null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SysMGR.UserInfo')),
            ],
        ),
    ]
