# Generated by Django 2.1 on 2018-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysMGR', '0004_auto_20180910_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, null=True)),
                ('facecode', models.CharField(default='', max_length=64, null=True)),
                ('note', models.CharField(default='', max_length=64, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='messgeinfo',
            old_name='messge',
            new_name='message',
        ),
    ]
