# Generated by Django 2.1 on 2018-09-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysMGR', '0005_auto_20180926_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceInfo',
        ),
    ]
